# AeroSpace Configuration File

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Start AeroSpace at login
start-at-login = true

after-startup-command = []
automatically-unhide-macos-hidden-apps = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

# Layout Switching
alt-shift-comma = 'layout accordion horizontal vertical'
alt-shift-period = 'layout tiles horizontal vertical'

# Focus movement
alt-i = 'focus up'
alt-j = 'focus left'
alt-k = 'focus down'
alt-l = 'focus right'

# Window movement 
alt-ctrl-i = 'move up'
alt-ctrl-j = 'move left'
alt-ctrl-k = 'move down'
alt-ctrl-l = 'move right'

# Window resizing
alt-ctrl-equal = 'resize smart +50'
alt-ctrl-minus = 'resize smart -50'

# Fullscreen
alt-enter = 'fullscreen'

# Workspaces
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'